; Listing generated by Microsoft (R) Optimizing Compiler Version 19.31.31105.0 

	TITLE	D:\Language C\HashTable\HashTable\Release\HashTable_Verify.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?HashTableVerifyInit@@YAHPBUHashTable@@@Z	; HashTableVerifyInit
; Function compile flags: /Ogtp
; File D:\Language C\HashTable\HashTable\HashTable\HashTable_Verify.cpp
;	COMDAT ?HashTableVerifyInit@@YAHPBUHashTable@@@Z
_TEXT	SEGMENT
_table$ = 8						; size = 4
?HashTableVerifyInit@@YAHPBUHashTable@@@Z PROC		; HashTableVerifyInit, COMDAT

; 14   : {

	push	ebp
	mov	ebp, esp

; 15   : 	assert(table);
; 16   : 
; 17   : 	//HASH_TABLE_ASSERT_STATUS;
; 18   : 
; 19   : 	if (table->Status    != HASH_TABLE_ERR_NO_ERRORS ||
; 20   : 		table->ExtStatus != 0 ||
; 21   : 		table->ListCount != 0 ||

	mov	eax, DWORD PTR _table$[ebp]
	cmp	DWORD PTR [eax+12], 0
	jne	SHORT $LN4@HashTableV
	cmp	DWORD PTR [eax+16], 0
	jne	SHORT $LN4@HashTableV
	cmp	DWORD PTR [eax+4], 0
	jne	SHORT $LN4@HashTableV
	mov	eax, DWORD PTR [eax+8]
	neg	eax
	sbb	eax, eax
	and	eax, 8

; 25   : 	}
; 26   : 	else
; 27   : 	{
; 28   : 		return HASH_TABLE_ERR_NO_ERRORS;
; 29   : 	}
; 30   : }

	pop	ebp
	ret	0
$LN4@HashTableV:

; 22   : 		table->Lists     != nullptr)
; 23   : 	{
; 24   : 		return HASH_TABLE_ERR_INIT;

	mov	eax, 8

; 25   : 	}
; 26   : 	else
; 27   : 	{
; 28   : 		return HASH_TABLE_ERR_NO_ERRORS;
; 29   : 	}
; 30   : }

	pop	ebp
	ret	0
?HashTableVerifyInit@@YAHPBUHashTable@@@Z ENDP		; HashTableVerifyInit
_TEXT	ENDS
END
