; Listing generated by Microsoft (R) Optimizing Compiler Version 19.31.31105.0 

	TITLE	D:\Language C\HashTable\HashTable\Release\main.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_main
EXTRN	__imp__SetConsoleCP@4:PROC
EXTRN	__imp__SetConsoleOutputCP@4:PROC
EXTRN	?TestHashTable_OptimizationInsertRemove@@YAXXZ:PROC ; TestHashTable_OptimizationInsertRemove
EXTRN	?LogsConstructor@@YAHXZ:PROC			; LogsConstructor
EXTRN	?LogsDestructor@@YAXXZ:PROC			; LogsDestructor
; Function compile flags: /Ogtp
; File D:\Language C\HashTable\HashTable\main.cpp
;	COMDAT _main
_TEXT	SEGMENT
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC						; COMDAT

; 13   : 	SetConsoleCP(1251);

	push	1251					; 000004e3H
	call	DWORD PTR __imp__SetConsoleCP@4

; 14   : 	SetConsoleOutputCP(1251);

	push	1251					; 000004e3H
	call	DWORD PTR __imp__SetConsoleOutputCP@4

; 15   : 
; 16   : 	LogsConstructor();

	call	?LogsConstructor@@YAHXZ			; LogsConstructor

; 17   : 
; 18   : 	//TestHashTable_Sheakspear();
; 19   : 
; 20   : 	//TestHashTable_OptimizationFind();
; 21   : 
; 22   : 	TestHashTable_OptimizationInsertRemove();

	call	?TestHashTable_OptimizationInsertRemove@@YAXXZ ; TestHashTable_OptimizationInsertRemove

; 23   : 
; 24   : 	LogsDestructor();

	call	?LogsDestructor@@YAXXZ			; LogsDestructor

; 25   : }

	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
